#!/usr/bin/env python

def create_data_version_javascript(target, source):
	import hashlib
	hash_md5 = hashlib.md5()
	length = 0
	with open(str(source), "rb") as f:
		for chunk in iter(lambda: f.read(4096), b""):
			length += len(chunk)
			hash_md5.update(chunk)
	hash = hash_md5.hexdigest()

	with open(str(target), 'w') as f:
		f.write('// autogenerated file, do not edit\n')
		f.write('// This is the md5 hash of the data file expected\n')
		f.write('var endlessSkyDataVersion = "')
		f.write(hash)
		f.write('";\nvar endlessSkyDataSize = ')
		f.write(str(length))
		f.write(';\n')

if __name__ == '__main__':
	import sys
	source, target = sys.argv[1:]
	create_data_version_javascript(target, source)
